### PR TITLE
Dev/gfdl

### PR DESCRIPTION
**Pull request by feiyulu**

### CODE REVIEW

**Comment by feiyulu** [comment]
I have merged all the name changed from dev/profiles to my dev/GFDL. Once this PR is completed, both our dev/GFDL should have my latest code and the new names.

**Comment by MJHarrison-GFDL** [comment]
obs_def_type is not available . Is it possible to bring this into MOM6_DA_hooks?

**Comment by feiyulu** [comment]
The obs_def_type is also used by Xiaosong in ADA, so we may have to find another solution instead of moving it to ocead_da_types

**Comment by feiyulu** [comment]
I'm thinking about defining another variable in ocean_da_types for the forward operator of ODA, which could also potentially help with our future effort in the FO. If we are to come up with a more advanced FO, the current obs_def_type cannot be used anyway.

**Pull request merged**
